### ISSUE TITLE
Add support for scrollbars and/or Maya edit widget

### ISSUE THREAD

**Issue by fredrikz** [Srekel/the-debuginator#39] opened 2020-04-03 11:22 UTC
Add support for scrollbars, to be able to tweak values

or better yet

Add support for "Maya edit widget", which lets users either enter a value, have +- buttons for current value, or can manipulate current value by mouse-drag

**Comment by Srekel** [comment] 2020-04-03 11:25
Duplicate of #16 :D

**Closed as completed by Srekel** 2020-04-03 11:25 UTC
